### ISSUE TITLE
请问 现在可以用来部署到生产环境吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [nk-akun/NeighborBBS#1]

**Comment by nk-akun** [comment]
可以的，功能方面目前测试没有问题，高并发场景下需要保证数据库性能，也非常欢迎任何形式的contribution.

**Comment by Yakumo-Yukari** [comment]
> 可以的，功能方面目前测试没有问题，高并发场景下需要保证数据库性能，也非常欢迎任何形式的contribution.

好的 谢谢解答
